# See https://taskfile.dev for more information
version: '3'

tasks:
  build:program:
    cmds:
      # Make the destination directory
      - mkdir -p bin

      # Compile the program
      - g++ {{if eq .VERBOSE "true"}} -g{{end}} -I {{.INCLUDE}} src/main.cpp -o bin/main
    vars:
      # Headers
      INCLUDE: /usr/include/eigen3
    desc: Build the program
    silent: true
    sources:
      - src/main.cpp
    generates:
      - bin/main

  build:proxy:
    cmds:
      # Make the destination directory
      - mkdir -p bin

      # Compile the proxy
      - g++ {{if eq .VERBOSE "true"}}-D VERBOSE -g{{end}} src/proxy.cpp -o bin/proxy
    desc: Build the proxy
    silent: true
    sources:
      - src/proxy.cpp
    generates:
      - bin/proxy

  symbols:program:
    cmds:
      - nm -C bin/main | grep Eigen::internal::general_matrix_matrix_product
    deps:
      - build:program
    desc: Lists the relevant (filtered) symbols from the program
    silent: true

  symbols:proxy:
    cmds:
      - nm -C bin/proxy | grep run
    deps:
      - build:proxy
    desc: Lists the relevant (filtered) symbols from the proxy
    silent: true

  clean:
    cmds:
      # Delete the directory
      - cmd: rm bin -r
        ignore_error: true
    desc: Clean everything
    silent: true

  run:no-proxy:
    cmds:
      - bin/main
    deps:
      - build:program
    desc: Run the program without the proxy
    silent: true

  run:proxy:
    cmds:
      - bin/proxy bin/main
    deps:
      - build:program
      - build:proxy
    desc: Run the program with the proxy
    silent: true
