# See https://taskfile.dev for more information
version: '3'

vars:
  DYNAMORIO: '{{default "/usr/local/lib/dynamorio" .DYNAMORIO_HOME}}'

tasks:
  build:program:
    cmds:
      # Make the destination directory
      - mkdir -p bin

      # Compile the program
      - g++ {{if eq .DEBUG "true"}} -g{{end}} src/main.cpp src/simple_math.cpp src/simple_math.hpp -o bin/main
    desc: Build the program
    label: 'build:program (Debug: {{eq .DEBUG "true"}})'
    silent: true
    sources:
      - src/main.cpp
      - src/simple_math.cpp
      - src/simple_math.hpp
    generates:
      - bin/main

  build:proxy:
    cmds:
      # Generate Makefiles
      - cmake -D DynamoRIO_DIR={{.DYNAMORIO}}/cmake -B lib .

      # Build
      - cmake --build lib
    desc: Build the proxy
    label: 'build:proxy (DynamoRIO: {{.DYNAMORIO}})'
    silent: true
    sources:
      - CMakeLists.txt
      - src/proxy.c
    generates:
      - lib/*

  symbols:program:
    cmds:
      - nm -C bin/main | grep add
    deps:
      - build:program
    desc: Lists the relevant (filtered) symbols from the program
    silent: true

  symbols:proxy:
    cmds:
      - nm -DC lib/libproxy.so | grep dr_client_main
    deps:
      - build:proxy
    desc: Lists the relevant (filtered) symbols from the proxy
    silent: true

  clean:
    cmds:
      # Delete the directories
      - cmd: rm bin lib -r
        ignore_error: true
    desc: Clean everything
    silent: true

  run:no-proxy:
    cmds:
      - bin/main
    deps:
      - build:program
    desc: Run the program without the proxy
    silent: true

  run:proxy:
    cmds:
      - '{{.DYNAMORIO}}/bin64/drrun -c lib/libproxy.so -- bin/main'
    deps:
      - build:program
      - build:proxy
    desc: Run the program with the proxy
    label: 'run:proxy (DynamoRIO: {{.DYNAMORIO}})'
    silent: true
