# See https://taskfile.dev for more information
version: '3'

vars:
  DYNAMORIO: '{{default "/usr/local/lib/dynamorio" .DYNAMORIO_HOME}}'

tasks:
  build:program:
    cmds:
      # Make the destination directory
      - mkdir -p bin

      # Compile the program ("-O1 -mpush-args" ensure the arguments are passed via the stack instead of registers)
      - g++ {{if eq .DEBUG "true"}} -g{{end}} -O1 -mpush-args src/main.cpp src/simple_math.cpp src/simple_math.hpp -o bin/main
    desc: Build the program
    silent: true
    sources:
      - src/main.cpp
      - src/simple_math.cpp
      - src/simple_math.hpp
    generates:
      - bin/main

  build:proxy:
    cmds:
      # Make the build directory
      - mkdir -p build

      # Generate Makefiles
      - cmake -D DynamoRIO_DIR={{.DYNAMORIO}}/cmake -B build .
      - cmake --build build
    desc: Build the proxy
    silent: true
    sources:
      - src/proxy.c
    generates:
      - build

  symbols:program:
    cmds:
      - nm -C bin/main | grep add
    deps:
      - build:program
    desc: Lists the relevant (filtered) symbols from the program
    silent: true

  symbols:proxy:
    cmds:
      - nm -DC build/libproxy.so | grep dr_client_main
    deps:
      - build:proxy
    desc: Lists the relevant (filtered) symbols from the proxy
    silent: true

  clean:
    cmds:
      # Delete the directories
      - cmd: rm bin build -r
        ignore_error: true
    desc: Clean everything
    silent: true

  run:no-proxy:
    cmds:
      - bin/main
    deps:
      - build:program
    desc: Run the program without the proxy
    silent: true

  run:proxy:
    cmds:
      - '{{.DYNAMORIO}}/bin64/drrun -c build/libproxy.so -- bin/main'
    deps:
      - build:program
      - build:proxy
    desc: Run the program with the proxy
    silent: true
